# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Faculty', verbose_name='Wydział')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.FieldOfStudy', verbose_name='Kierunek')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenci',
            },
        ),
        migrations.CreateModel(
            name='StudentTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_time_tables', to='students.Student')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_table_student', to='schedules.TimeTable')),
            ],
            options={
                'verbose_name': 'Plan zajęć Studenta',
                'verbose_name_plural': 'Plany zajęć Studenta',
            },
        ),
    ]
