# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 09:29
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('semester', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kursy',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('degree', models.CharField(choices=[('BSC', 'I stopień inżynierskie'), ('BCH', 'I stopień licencjackie'), ('MST', 'II stopień licencjackie'), ('MSC', 'II stopień inżynierskie')], default='BSC', max_length=3)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='schedules.Faculty')),
            ],
            options={
                'verbose_name': 'Kierunek',
                'verbose_name_plural': 'Kierunki',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('W', 'wykład'), ('C', 'ćwiczenia'), ('L', 'laboratorium'), ('P', 'projekt'), ('S', 'seminarium')], max_length=1)),
                ('start_time', models.TimeField(choices=[(datetime.time(7, 30), '7:30'), (datetime.time(8, 15), '8:15'), (datetime.time(9, 15), '9:15'), (datetime.time(10, 15), '10:15'), (datetime.time(11, 15), '11:15'), (datetime.time(12, 15), '12:15'), (datetime.time(13, 15), '13:15'), (datetime.time(14, 15), '14:15'), (datetime.time(15, 15), '15:15'), (datetime.time(16, 10), '16:10'), (datetime.time(17, 5), '17:05'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 55), '18:55'), (datetime.time(19, 50), '19:50')])),
                ('end_time', models.TimeField(choices=[(datetime.time(8, 15), '8:15'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 55), '16:55'), (datetime.time(17, 50), '17:50'), (datetime.time(18, 45), '18:45'), (datetime.time(19, 40), '19:40'), (datetime.time(20, 35), '20:35')])),
                ('day', models.IntegerField(choices=[(None, 'wybierz dzień zajęć'), (0, 'poniedziałek'), (1, 'wtorek'), (2, 'środa'), (3, 'czwartek'), (4, 'piątek'), (5, 'sobota'), (6, 'niedziela')])),
                ('week_type', models.CharField(choices=[('PN', 'normalny'), ('P', 'parzysty'), ('N', 'nieparzysty')], default='PN', max_length=2)),
                ('place', models.CharField(max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schedules.Course')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupy',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(0, 'lic.'), (1, 'inż.'), (2, 'mgr'), (3, 'mgr inż.'), (4, 'dr'), (5, 'dr inż.'), (6, 'dr hab.'), (7, 'dr hab. inż.'), (8, 'prof. dr hab.'), (10, 'prof dr hab. inż')])),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Prowadzący',
                'verbose_name_plural': 'Prowadzący',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='schedules.FieldOfStudy')),
                ('groups', models.ManyToManyField(related_name='time_tables', to='schedules.Group')),
            ],
            options={
                'verbose_name': 'Plan zajęć',
                'verbose_name_plural': 'Plany zajęć',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='lecturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schedules.FieldOfStudy'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('code', 'start_time', 'end_time', 'day', 'week_type')]),
        ),
    ]
